python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=1 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=1 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=1 --mse_threshold=2.0 --shift_quant_mode='max' 


# python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=1 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=2 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=4 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=8 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=16 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=32 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=64 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=128 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=256 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=512 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=2 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=1024 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=1 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=2 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=4 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=8 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=16 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=32 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=64 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=128 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=256 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=512 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=3 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=1024 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=1 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=2 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=4 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=8 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=16 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=32 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=64 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=128 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=256 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=512 --mse_threshold=2.0 --shift_quant_mode='max' 
# python ShiftedScaleQuant.py --test=True --n_bits_w=4 --n_bits_a=4 --w_scale_method=max --run_device=cuda:1 --mse_level=1024 --mse_threshold=2.0 --shift_quant_mode='max' 